# Generated by Django 4.1 on 2022-08-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
