# Generated by Django 4.1 on 2022-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_token_user_remove_tokens_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
