# Generated by Django 4.1 on 2022-08-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
